# Site settings
author: Devin Wilson
title: 1st CLI Application
header-img: img/home-bg.png
email: craigvin84@yahoo.com
copyright_name: Devin Wilson
description: > # this means to ignore newlines until "baseurl:"
  Corona Virus Counter
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  RSon84

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
